services:
  web:
    image: adernild/dernild.dev
    container_name: dernild-dev
    restart: unless-stopped
    extends:
      file: ../../common/base.yml
      service: default
    networks:
      - internal

networks:
  internal:
    external: true
