services:
  dr-neo4j:
    extends:
      file: ../../common/neo4j.yml
      service: neo4j
    env_file: .env
    expose:
      - 7474
      - 7687
    networks:
      - internal

networks:
  internal:
    external: true
