services:
  mcp-rs:
    image: adernild/dr-mcp:latest
    container_name: dr-mcp-rs
    extends:
      file: ../../common/base.yml
      service: default
    restart: unless-stopped
    env_file: .env
    networks:
      - mcp
      - internal
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:2026.04.0-community-trixie
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
    networks:
      - mcp
    volumes:
      - neo4j-data:/data


volumes:
  neo4j-data:

networks:
  internal:
    external: true
  mcp:
