services:
  mcp-rs:
    image: adernild/dr-mcp:latest
    container_name: dr-mcp-rs
    extends:
      file: ../../common/base.yml
      service: default
    restart: unless-stopped
    env_file: .env
    networks:
      - mcp
      - internal
    depends_on:
      - neo4j

  neo4j:
    extends:
      file: ../../common/neo4j.yml
      service: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
    networks:
      - mcp
    volumes:
      - neo4j-data:/data


volumes:
  neo4j-data:

networks:
  internal:
    external: true
  mcp:
