services:
  neo4j:
    image: neo4j:2026.04.0-community-trixie
    extends:
      file: base.yml
      service: default
    expose:
      - 7474
      - 7687
    labels:
      - "traefik.http.routers.${TRFK_ROUTER}.middlewares=cors-neo4j"
      - "traefik.http.middlewares.cors-neo4j.headers.customResponseHeaders.Access-Control-Allow-Origin=https://${TRFK_HOSTNAME} https://${TRFK_HOSTNAME}:7687"

      - "traefik.http.routers.${TRFK_ROUTER}-bolt.rule=Host(`${TRFK_HOSTNAME}`)"
      - "traefik.http.routers.${TRFK_ROUTER}-bolt.entrypoints=bolt"
      - "traefik.http.services.${TRFK_ROUTER}-bolt.loadbalancer.server.port=7687"
