services:
  neo4j:
    image: neo4j:2026.04.0-community-trixie
    extends:
      file: base.yml
      service: default
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    labels:
      - "traefik.http.routers.${TRFK_ROUTER}.service=${TRFK_ROUTER}"
      - "traefik.http.routers.${TRFK_ROUTER}.middlewares=cors-neo4j"
      - "traefik.http.middlewares.cors-neo4j.headers.customResponseHeaders.Access-Control-Allow-Origin=https://${TRFK_HOSTNAME} https://${TRFK_HOSTNAME}:7687"

      - "traefik.tcp.routers.${TRFK_ROUTER}-bolt.rule=HostSNI(`${TRFK_HOSTNAME}`)"
      - "traefik.tcp.routers.${TRFK_ROUTER}-bolt.entrypoints=bolt"
      - "traefik.tcp.routers.${TRFK_ROUTER}-bolt.service=${TRFK_ROUTER}-bolt"
      - "traefik.tcp.services.${TRFK_ROUTER}-bolt.loadbalancer.server.port=7687"
      - "traefik.tcp.routers.${TRFK_ROUTER}-bolt.tls=true"
      - "traefik.tcp.routers.${TRFK_ROUTER}-bolt.tls.certResolver=letsencrypt"
