entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http3:
      advertisedPort: 443
    http:
      middlewares:
        - secure-chain@file
      tls:
        options: default
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: alex@dernild.dk
      storage: /letsencrypt/acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 5

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///socket/traefik.sock"
    network: internal
  file:
    directory: "/etc/traefik/rules"
    watch: true

api:
  dashboard: true
  insecure: true
  debug: true

log:
  level: DEBUG
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: "traefik"

ping:
  entrypoint: "traefik"
