entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: dernild.com
            sans:
              - "*.dernild.com"

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: alex@dernild.dk
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
      delayBeforeCheck: 5
      keyType: EC256

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///socket/traefik.sock"
    network: internal
  file:
    directory: "/etc/traefik/rules"
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: DEBUG
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: "traefik"

ping:
  entrypoint: "traefik"
